MVC/PizzaPlace/PizzaPlace.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PizzaPlace.WebApp.Models;

namespace PizzaPlace.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/PizzaPlace/PizzaPlace.WebApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaPlace.Library;
using PizzaPlace.WebApp.Models;
using PizzaPLace.DataAccess;
using PizzaPlaceLibrary;

namespace PizzaPlace.WebApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly PizzaPlaceContext _context;
        public OrdersRepository Repo;
        public decimal Order_total;
        public int Count;

        public OrdersController(PizzaPlaceContext context, OrdersRepository repo)
        {
            _context = context;
            Repo = repo;

        }
        

        

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var pizzaPlaceContext = _context.Orders.Include(o => o.Location).Include(o => o.Users);
            return View(await pizzaPlaceContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            int orderid = int.Parse(TempData.Peek("orderid").ToString());
            //decimal order_total = decimal.Parse(TempData.Peek("order_total").ToString());
            //Repo.UpdateTotal(order_total, orderid);
            //var  order_pizzas = Repo.GetPizzasofOrder(orderid);



            var orders = await _context.Orders
                .Include(o => o.Location)
                .Include(o => o.Users)
                .FirstOrDefaultAsync(m => m.OrderId == orderid);


            //foreach (var item in order_pizzas)
            //{
            //    TempData["pizza_name"] = item.Name;
            //    TempData["pizza_size"]= item.Size;
            //    TempData["pizza_price"] = item.Price;
            //}

            //var oders2 = _context.Orders.Where(q => q.OrderId == orderid);



            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        //GET: place order
        public ActionResult PlaceOrder(Users user)
        {

            ViewModel myModel = new ViewModel();

            return View(myModel);
        }

        //POST: placer order
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PlaceOrder(IFormCollection viewCollection,ViewModel myModel, Users user)
        {
            //int userid = int.Parse(viewCollection["UseridTD"].ToString());
            //TempData["result"] = userid;
           
            int UseridTD = int.Parse(TempData.Peek("userid").ToString());
            int LocationTD = int.Parse(TempData.Peek("locationid").ToString());
            string NameTD = TempData.Peek("firstname").ToString();
            string LastnameTD = TempData.Peek("lastname").ToString();
            string PhoneTD = TempData.Peek("phone").ToString();


            PizzaModel newPizza = new PizzaModel();
            OrderModel order = new OrderModel();

            ViewData["msg"] = "Add a Pizza";
            if (Count == 11)
            {
                ViewData["msg"] = "You can create only one more pizza, (max of 12 pizzas per order)";
            }
            else if(Count == 12)
            {
                ViewData["msg"] = "You have reach your maximun of pizzas per order (12 pizzas), Please place your order ";
                return RedirectToAction(nameof(PlaceOrder));
            }

            //ViewModel myModel = new ViewModel();

            newPizza.Crust = int.Parse(viewCollection["SelectedCrust"].ToString());
            newPizza.Size = viewCollection["SelectedSize"];
            newPizza.Name = viewCollection["SelectedPizza"];

            string sauce = viewCollection["SelectedSauce"];




            //  order.LocationId = user.LocationId;
            order.LocationId = user.LocationId;
            order.OrderTotal = 0;
            order.UsersId = user.UsersId;



            var toppings = new List<string>();
            toppings.Add(newPizza.Name);

            Pizzas pizza = new Pizzas
            {
                Crust = newPizza.Crust,
                Size = newPizza.Size,
                Name = newPizza.Name
            };

            //calculate price
            decimal S = 6, M = 8, L = 12;
            //quantity of topppings batch for pizza size

            if (pizza.Size == "S")
            {
                pizza.Price = S;


                Order_total = int.Parse(TempData.Peek("order_total").ToString());
                Order_total += S;
                TempData["order_total"] = Order_total;
            }
            else if (pizza.Size == "M")
            {
                pizza.Price = M;
                Order_total = int.Parse(TempData.Peek("order_total").ToString());
                Order_total += M;
                TempData["order_total"] = Order_total;

            }
            else
            {
                pizza.Price = L;
                Order_total = int.Parse(TempData.Peek("order_total").ToString());
                Order_total += L;
                TempData["order_total"] = Order_total;

            }
            

            //check availability of ingredients for each pizza
            bool availability = Repo.CheckInventory(toppings, pizza, sauce, LocationTD);
            if (availability == true)
            {
                // take out toppings from db
                Repo.MinusToppings(toppings, pizza, sauce, LocationTD);

                //add pizza
                Repo.AddPizzas(pizza.Size, pizza.Price, pizza.Name, pizza.Crust);
                Repo.SaveChanges();

                if (TempData.Peek("Count").ToString() == "1")
                {
                    Count = 1;

                }
                else
                {
                    Count = int.Parse(TempData.Peek("Count").ToString());
                }


                if (Count < 2)//only if the order is new is going to be created
                {
                    //add order
                    Repo.AddOrder(UseridTD, LocationTD, Order_total);

                }
                // increment counter to know next time, that this is not  a new order.
                Count++;
                TempData["Count"] = Count;
                

                //add orderPizza
                int? order_id = Repo.GetOrderByUserId(UseridTD);
                int? pizza_id = Repo.GetPizzaIdBySize(pizza.Name, pizza.Size);
                TempData["orderid"] = order_id;
                Repo.AddOrderPizza(order_id, pizza_id);
                   

            }
            else
            {
                ViewData["msg"] = "Not enough reseources to complete your order, Please choose again...";
                return RedirectToAction(nameof(PlaceOrder));
            }


            return RedirectToAction(nameof(PlaceOrder));


        }

        //GET: invoice
    
        public IActionResult Invoice(int? id)
        {
            int orderid = int.Parse(TempData.Peek("orderid").ToString());

            var orders = _context.Orders
                .Include(o => o.Location)
                .Include(o => o.Users)
                .FirstOrDefaultAsync(m => m.OrderId == orderid );


           

            return View(orders);
        }

        ////POST: invoice
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Invoice()
        //{
        //    return View();
        //}

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "Name");
            ViewData["UsersId"] = new SelectList(_context.Users, "UsersId", "FirstName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,UsersId,LocationId,OrderTime,Price,OrderTotal")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "Name", orders.LocationId);
            ViewData["UsersId"] = new SelectList(_context.Users, "UsersId", "FirstName", orders.UsersId);
            return View(orders);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "Name", orders.LocationId);
            ViewData["UsersId"] = new SelectList(_context.Users, "UsersId", "FirstName", orders.UsersId);
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,UsersId,LocationId,OrderTime,Price,OrderTotal")] Orders orders)
        {
            if (id != orders.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);

MVC/PizzaPlace/PizzaPlace.WebApp/Controllers/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaPLace.DataAccess;

namespace PizzaPlace.WebApp.Controllers
{
    public class PizzasController : Controller
    {
        private readonly PizzaPlaceContext _context;

        public PizzasController(PizzaPlaceContext context)
        {
            _context = context;
        }

        // GET: Pizzas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pizzas.ToListAsync());
        }

        // GET: Pizzas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizzas = await _context.Pizzas
                .FirstOrDefaultAsync(m => m.PizzaId == id);
            if (pizzas == null)
            {
                return NotFound();
            }

            return View(pizzas);
        }

        // GET: Pizzas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pizzas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PizzaId,Name,Type,Size,Crust,Price")] Pizzas pizzas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pizzas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pizzas);
        }

        // GET: Pizzas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizzas = await _context.Pizzas.FindAsync(id);
            if (pizzas == null)
            {
                return NotFound();
            }
            return View(pizzas);
        }

        // POST: Pizzas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PizzaId,Name,Type,Size,Crust,Price")] Pizzas pizzas)
        {
            if (id != pizzas.PizzaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pizzas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PizzasExists(pizzas.PizzaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pizzas);
        }

        // GET: Pizzas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizzas = await _context.Pizzas
                .FirstOrDefaultAsync(m => m.PizzaId == id);
            if (pizzas == null)
            {
                return NotFound();
            }

            return View(pizzas);
        }

        // POST: Pizzas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pizzas = await _context.Pizzas.FindAsync(id);
            _context.Pizzas.Remove(pizzas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PizzasExists(int id)
        {
            return _context.Pizzas.Any(e => e.PizzaId == id);
        }
    }
}

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Create.cshtml
@model PizzaPLace.DataAccess.Users

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h3>@TempData["variable"] </h3>
<h4>Users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Delete.cshtml
@model PizzaPLace.DataAccess.Users

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LocationId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LocationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UsersId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Details.cshtml
@model PizzaPLace.DataAccess.Users

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LocationId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LocationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UsersId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Edit.cshtml
@model PizzaPLace.DataAccess.Users

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UsersId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Home.cshtml
@model IEnumerable<PizzaPLace.DataAccess.Users>
@{
    ViewData["Title"] = "Home";
}


<style>

    button {
        margin-top: 5px;
        margin-bottom: 5px;
        display: inline-block;
        display: inline;
        zoom: 1;
        vertical-align: middle;
        margin-left: 20px ;
        background-color: green;
    }

    h4 {
        display: inline-block;
        display: inline;
        zoom: 1;
        float: left;
        padding-top: 5px;
        text-align: left;
        width: 350px;
    }


</style>


<h1 align="center">Choose an Option</h1>

<table class="table">
    <thead>
        <tr>
            <th style="display: flex">
                <div class="form-group">
                    <h4>Display all pizzas</h4>
                    <button type="submit" class="btn btn-default "><a asp-area="" asp-controller="Pizzas" asp-action="Index">See Pizzas</a></button>
                </div>
            </th>
        </tr>
        <tr>
            <th>
                <h4> Display all Orders</h4>
                <div class="form-group">
                    <button type="submit" class="btn btn-default "><a asp-area="" asp-controller="Orders" asp-action="Index">See Orders</a></button>
                </div>
            </th>
        </tr>
        <tr>
            <th>
                <div class="form-group">
                    <h4> Search users by name</h4>
                    <button type="submit" class="btn btn-default "><a href="SearchUser">Search User</a></button>
                </div>
            </th>
        </tr>
        <tr>
            <th>
                <h4>Display all order history of a single location</h4>
                <div class="form-group">
                    <button type="submit" class="btn btn-default "><a href="#">Show History</a></button>
                </div>
            </th>
        </tr>
        <tr>
            <th>
                <h4>Display all order history of a user</h4>
                <div class="form-group">
                    <button type="submit" class="btn btn-default "><a href="SearchUser"> Order History  </a></button>
                </div>
            </th>
        </tr>
        <tr>
            <th>
                <h4> Display All Users</h4>
                <div class="form-group">
                    <button type="submit" class="btn btn-default "><a href="index">See Users</a></button>
                </div>
            </th>
        </tr>
       

        <tr>
            @*<th>
                <h4> User - Order - Pizzas</h4>
                <div class="form-group">
                    <button type="submit" class="btn btn-default "><a asp-area="" asp-controller="PizzaOrder" asp-action="Index">Go</a></button>
                </div>
            </th*@>
        </tr>
        @*<th>
            @Html.DisplayNameFor(model => model.DefaultLocationFkNavigation)
        </th>*@
       
       
    </thead>
</table>

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Index.cshtml
@model IEnumerable<PizzaPLace.DataAccess.Users>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UsersId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UsersId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UsersId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/Register.cshtml
@model PizzaPlace.WebApp.Models.UserModel

@{
    ViewData["Title"] = "Welcome";
}

<style>

    button {
        margin-top: 5px;
        margin-bottom: 5px;
        display: inline-block;
        display: inline;
        zoom: 1;
        vertical-align: middle;
        margin-left: 20px;
        background-color: #4CAF50;
    }

    h1{
        font-size: 50px;
        
      
    }

    h4 {
        display: inline-block;
        display: inline;
        zoom: 1; 
        float: left;
        padding-top: 5px;
        text-align: left;
        width: 350px;
    }
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

   


   
</style>




<h1 style="color: darkgreen;">Welcome to Pizza Place</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UsersId" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Continue" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/PizzaPlace/PizzaPlace.WebApp/Views/Users/SearchUser.cshtml
@model PizzaPLace.DataAccess.Users
@{
    ViewData["Title"] = "SearcUser";
}
<h2 align="center">User Search</h2>
<div>
    <h4></h4>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="SearcUser">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="UsersId" />
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <input type="submit" value="Search" class="btn btn-default" />
            </form>
        </div>
    </div>
    <hr />
    <dl>
        <dt>
            <h3>@TempData["Error"]</h3>
        </dt>
        <dt>
            <h3>ID:@TempData["id"]</h3>
        </dt>
        <dt>
            <h3>Name:@TempData["name"]</h3>
        </dt>
        <dt>
            <h3>Last Name:@TempData["last"]</h3>
        </dt>
        <dt>
            <h3>Phone:@TempData["phone"]</h3>
        </dt>
        <dt>
            <h3>Location:@TempData["loc"]</h3>
        </dt>
    </dl>
    <a asp-action="Home">Back to Home</a>
</div>